### ISSUE TITLE
Running tests is broken on Edge 12-18

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#1007]
Oops. I'm not sure when it broke.

**Comment by foolip** [comment]
I'm pretty sure the problem is the `mediaDevices.getUserMedia` call which will just hang forever. But if that's right, this will have been broken since https://github.com/foolip/mdn-bcd-collector/pull/514. @vinyldarkscratch do you recall if you've used selenium.js to get results for Edge since then, or if it's all been manual and clicking the prompt to allow camera access?

**Comment by foolip** [comment]
This was fixed by https://github.com/foolip/mdn-bcd-collector/pull/1008.

**Comment by vinyldarkscratch** [comment]
If I remember correctly, this was indeed an issue I faced, and for the time being had mitigated with manual results collections (to reach the 90% goal quicker).

I remember also dealing with issues in certain Chrome versions due to fatal bugs, and accordingly had developed an "ignore" system in the Selenium script -- perhaps that may be something to take advantage of here?

**Comment by foolip** [comment]
@vinyldarkscratch that's a good idea! I've sent https://github.com/foolip/mdn-bcd-collector/pull/1017 to do that.
