### ISSUE TITLE
Missing non-standard IE IDL

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#1067]
e.g. `api.XDomainRequest` has data in BCD

https://gist.github.com/MSEdge/63a18da22c1da2639b1a has IDL for a bunch of IE-but-removed-in-Edge(HTML) stuff, though the diffing seems to be slightly imperfect.

**Comment by foolip** [comment]
I added `XDomainRequest` in #1039, but haven't made a new release since then, but you can see it in staging:
https://staging-dot-mdn-bcd-collector.appspot.com/tests/api/XDomainRequest

Since the coverage of IDL is fairly high now, I'm thinking that the approach for keeping it good should be to write a page that looks up everything on the global object and what things see to be on each interface, similar in principle to Web Confluence, and compares that against what is in BCD. Then one can have a look at that page in recent browsers and spot misses over time.

Things that aren't in any current browser aren't as important to add, although I realize I've probably already added a lot of custom IDL in that category, just to be sure.

**Comment by gsnedders** [comment]
`api.XDomainRequest` came up because it's something that exists in BCD; the priority order is probably: things in BCD, things in any current browser, things in any historic browser?

**Comment by foolip** [comment]
Indeed, I found `XDomainRequest` using the find-missing script because it's in BCD. https://github.com/foolip/mdn-bcd-collector/tree/find-missing-burndown has some ignore-lists to filter it, and this is what remains in APIs:

api.CSSNumericArray.CSSNumericValue
api.CSSUnparsedValue.CSSUnparsedSegment
api.CustomElementRegistry.builtin
api.DataTransferItemList.DataTransferItem
api.EventListener
api.EventListener.handleEvent
api.FileSystemDirectoryEntry.removeRecursively
api.FormData.SupportForOf
api.HTMLAnchorElement.toString
api.HTMLAreaElement.toString
api.NodeFilter
api.NodeFilter.acceptNode
api.RTCDataChannel.sctp-sdp-21
api.RTCSessionDescriptionCallback
api.SourceBufferList.SourceBuffer
api.TrackDefaultList.TrackDefault
api.WorkerGlobalScope.console
api.XRFrameRequestCallback

A mix of various issues, but overall not much left. Expanding coverage of CSS and JS is probably more important now, as you've noted in other issues.

**Comment by foolip** [comment]
`XDomainRequest` was removed in https://github.com/mdn/browser-compat-data/pull/11438 and https://github.com/openwebdocs/mdn-bcd-collector has a script for enumerating what's missing tests still.

`npm run find-missing-features` does list some APIs that we could add IDL for still, but it's nothing very dramatic at this point, and it's not IE stuff.
