### ISSUE TITLE
Avoid adding ranges in update-bcd where current data already satisfies them

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#1068]
e.g. don't do this:

```
-            "safari": {
-              "version_added": "1",
-              "version_removed": "10"
-            },
+            "safari": [
+              {
+                "version_added": "≤6",
+                "version_removed": "10"
+              },
+              {
+                "version_added": "1",
+                "version_removed": "10"
+              }
+            ],
```

**Comment by foolip** [comment]
Absolutely! Combining two arrays of support statements is surprisingly hard and there are lots of cases not handled, and some are handled poorly. I've documented some of what's wrong in https://github.com/foolip/mdn-bcd-collector/issues/571.

But this is a case I think must be possible to fix without changing the overall approach.

Note that the reason a lot of weird changes like this are left is because we've mostly been picking the good stuff from the changes produced, and not gotten anywhere near burning down *all* proposed changes to find all issues like this.

**Comment by foolip** [comment]
Note to self: this is happening for `api.Document.createEntityReference`.

**Comment by foolip** [comment]
This should no longer be happening after https://github.com/foolip/mdn-bcd-collector/pull/1088. The script is now a bit more conservative, so there *may* also be correct edits no longer being made. The total amount of changes makes this hard to vet, but I didn't find anything concerning when sampling the diff before and after the change.
