### ISSUE TITLE
Copy result to clipboard

### ISSUE THREAD

**Issue by ddbeck** [foolip/mdn-bcd-collector#1157]
This is a nice-to-have feature proposal. I understand this is ultra-low priority.

Sometimes, I'll use the collector to confirm a reported BCD quality issue. It'd be great if there was some sort of human-readable text I could copy with the browser, feature name, and result. For example, `Firefox 90 - api.Window.alert (Window exposure) - true`. Even better would be a one-click copy-to-clipboard button. This would help me keep track of what I've done and report it back out to the original reporter.

If you're entertaining pull requests, I'm happy to give this a try myself, though I'm not sure where to start looking to make changes. A pointer in the right direction would help. Thank you!

**Comment by foolip** [comment]
@ddbeck that sounds like a very reasonable feature, one that I would find useful too.

The natural place to put this is probably next to the individual results, which are in `<details>` elements. This structure is generated by JS after the tests have run, and it's done this way in order to do as little as possible before running tests that could fail or accidentally taint the tests. Here's the code you'd tweak:

https://github.com/foolip/mdn-bcd-collector/blob/b864c8b7fece7f18998f13b1eeae39f2499f669d/static/resources/harness.js#L598-L637

Being able to copy all the results on a page could also come in handy, and in fact maybe *just* that could suffice. If so, somewhere just outside that loop is probably the right place for it.

I think mdi-content-copy should work as an icon for this.

**Comment by foolip** [comment]
> If you're entertaining pull requests

Very much so! I'm not always a speedy reviewer though :)

**Comment by foolip** [comment]
@ddbeck I'm in the process of sunsetting this repo in favor of https://github.com/openwebdocs/mdn-bcd-collector. If you still want this as a feature, please file a new issue :)
