### ISSUE TITLE
Two reports for Firefox 1 in mdn-bcd-results

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#1341]
We got two of the same:
https://github.com/foolip/mdn-bcd-results/pull/2256
https://github.com/foolip/mdn-bcd-results/pull/2259

@vinyldarkscratch I suspect this was collected manually and accidentally duplicated. If that's right just close this issue. If not there might be an issue with the Selenium script.

Discovered as part of https://github.com/foolip/mdn-bcd-collector/pull/1340 because the reports weren't combined correctly.

**Comment by vinyldarkscratch** [comment]
As odd as it seems to have two results files for the same browser, especially since I've been removing dupes when I see them, these ones are two separate sets of tests!  Firefox 1 through 3.6 is collected manually since no CI has them (well, BrowserStack has 3 and 3.6, but we cap it at 4 since Selenium isn't available before then), and the tests run quite slow on these older Firefox versions, I run the tests in segments to prevent a crash (AKA, Window-scope APIs, then Worker, etc.).  When I was collecting Firefox 1 results, I accidentally submitted just the Window-scope results and closed the browser.  I didn't want to wait and run them all again, so I decided to run the remaining tests and submit it separately.

**Comment by foolip** [comment]
Got it, thanks for the explanation!
