### ISSUE TITLE
Requiring review for collector changes

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#1480]
@queengooborg, we've both been pushing a lot of changes without review, which has been good for velocity, but the collector is fairly stable now and I think we can afford to require code review. This would be done via branch protection rules, where passing CI is already required. WDYT?

**Comment by queengooborg** [comment]
Requiring review does sound good, and since CI passing is required we already must create PRs for code changes.  The one thing that has me on the fence about this is that there are only two of us on this project, and I'd only be actively working on the collector during contract.  Making a requirement for code review may cause delays in development, especially when I'm not on contact.

**Comment by foolip** [comment]
Let's turn it on for now, and we can turn it off again if only one of us is working on the project at some point in the future.

**Comment by foolip** [comment]
Now enabled.
