### ISSUE TITLE
Combining "X11" and "MacOS" in user agent string causes "Internal server error"

### ISSUE THREAD

**Issue by stp-ekioh** [foolip/mdn-bcd-collector#1891]
Was just testing the Flow browser with https://mdn-bcd-collector.appspot.com/, and spotted that using an X11 build on Mac just results in a white screen with the message "Internal server error".  The only difference between the working versions is the presence of "MacOS" rather than "Linux" in the browser's user-agent string.  For example, this works:

  Mozilla/5.0 (X11; Linux x86_64) EkiohFlow/5.17.0.36739 Flow/5.17.0 (like Gecko Firefox/89.0 rv:89.0)

but this results in "Internal server error":

  Mozilla/5.0 (X11; MacOS x86_64) EkiohFlow/5.17.0.36739 Flow/5.17.0 (like Gecko Firefox/89.0 rv:89.0)

Is there any chance that we could get this fixed?

Cheers!

**Comment by foolip** [comment]
@queengooborg can you check if this might be the UA string parser throwing an exception?

**Comment by queengooborg** [comment]
I'm thinking that it might just be.  The user agent string is able to parse the OS from the Linux version, but it doesn't seem to be able to do so for macOS.

One thing I've noticed is that the OS in Flow's user agent string is `(X11; MacOS x86_64)`, whereas in other browsers (Chrome, Safari, Firefox), I'm seeing `(Macintosh; Intel Mac OS X 10_15_7)`.  If I replace `MacOS x86_64` with `Intel Mac OS X 10_15_7`, that seems to fix the UA parser.  Maybe something to change upstream?

I'm going to tweak our code so that an unparseable UA string doesn't just crash the website.  Thank you for reporting this!

**Comment by foolip** [comment]
@queengooborg thanks for the speedy fix!
