### ISSUE TITLE
Snapshot built tests?

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#1908]
When opening a PR for BCD, I include a link to the collector to show the test that was used for the data.  However, these links will always show and run the latest version of a test, which means that other users won't have the same results as the PR's date in newer collector versions.  Additionally, open PRs during a collector update could have unintentional misinformation -- that is, if a PR is opened using a test that was updated in between PR authoring and reviewing, the reviewer may mistakenly think the results are from the new test.

We should keep snapshots of older test versions that we can hardlink back to for historical purposes, perhaps as a part of the release process.  In theory, this should also help us simplify the release script (and modifying it too) since we won't have to rely on Git commands to access the last branch.

**Comment by foolip** [comment]
I have been aware of this problem in particular with PRs that are in review for a long time, but in practice I haven't had a problem because of it. Have other reviewers pointed out this problem?

It would be fairly easy to archive tests.json for each release, but if we provide a way to show or even run the tests that will mean that we have to support the current tests.json format forever.

Maybe we could include the tests code directly into the PR descriptions instead?
