### ISSUE TITLE
Test if constructor is legal, not just if it exists

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#352]
From 8/10/2020 sync meetup.  Determine if a constructor is legal based upon `Interface.length`, and pass in the number of args that variable defines.  If the constructor returns a TypeError, it's unsupported.  Also, looking at the error message would help us determine if it's unsupported.

**Comment by vinyldarkscratch** [comment]
Fixed by #353.

**Comment by foolip** [comment]
I suspect that trying to update data based on the results will quickly reveal some things that need fixing. In particular there are probably some constructors which always throw an exception but still claim there are too few arguments, because the exception is thrown from the implementation rather than bindings. That's likely for placeholder code that the implementer would be harmless and indistinguishable from not having the constructor, or for flag-enabled constructors perhaps.

**Comment by vinyldarkscratch** [comment]
#374 and #382 have fixed this up a bit, so test results are more accurate.
