### ISSUE TITLE
Mysterious prefix/capitalization in test

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#405]
http://mdn-bcd-collector.appspot.com/api/TreeWalker/expandEntityReferences/ says that the generated test is `"TreeWalker" in self && "MSExpandEntityReferences" in TreeWalker.prototype`. What is the "MSExpandEntityReferences"?

**Comment by foolip** [comment]
This is also in http://mdn-bcd-collector.appspot.com/api/NodeIterator/, and what's even more strange is that only this member has the problem. I added the IDL for this attribute in bfaedcd74fd07e3271688c872946da9e9bb5e74e.

**Comment by vinyldarkscratch** [comment]
Ah, I see what's going on -- it's a little bit of a conflict with the prefix testing.  Since the tests are written in a dictionary format, it has a little compilation step which includes adding the prefix.  If it runs through all the prefixes and finds no support, the variable remains as the last tested prefix.

I'll see what I can do to get this fixed up!
