### ISSUE TITLE
Console API doesn't post updates correctly

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#418]
In BCD, the Console API is referred to as `api.Console` -- however, the WebIDL actually defines `console` as a namespace with no capitalization.  Since the identifiers are case-sensitive, this causes no updated results.

There's a few solutions I can think of:
- Rename the identifier in the build script -- hacky and special-casing, but it'll do the trick at least
- Rename the identifier in update-bcd -- also hacky and special-casing
- Make identifiers case-insensitive -- could cause unforseen issues in BCD

**Comment by foolip** [comment]
I've come across this before and I think there's been discussion in BCD, but I can't find the issue now.

The capitalization mismatch goes beyond BCD and has a bit of a history. console.* predates namespaces in Web IDL and I believe it was originally not implemented using IDL at all. At some point it was probably and interface named Console with an instance named console on the global object.

Since I don't know of any other capitalization mismatch, I think we can map it in this project and only generalize if there are more subtle name mismatches that we discover.

**Comment by foolip** [comment]
You can see some of the history behind this in https://github.com/whatwg/console/pull/66.
