### ISSUE TITLE
Trim /resources/harness.js to the minimum, generating more server-side

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#436]
https://github.com/foolip/mdn-bcd-collector/blob/main/static/resources/harness.js is a lot of code running in the browser and an indirection for a BCD reviewing looking at a test and trying to verify if it's testing the right thing.

It would help if more of this was done server-side. In particular:
- No `eval` anywhere, instead generate the code to run as a function to execute
- Should not need to know about global scopes, instead the right tests should be output depending on the scope
- No handling of prefixes, which makes it harder to see exactly what the full string tested was

**Comment by vinyldarkscratch** [comment]
In regards to the `eval` point, we won't exactly be able to avoid it.  Since functions aren't serializable objects, we can't send them to our workers (the `message` function only allows for objects that can be turned into strings).

With the scopes, won't we want to test all the APIs in all of the intended exposure sets?  That would allow us to automate features like `worker_support`.

Finally, with the prefix handling part, we can definitely simplify that more, creating prefix tests as separate test endpoints (as proposed in #431).

**Comment by foolip** [comment]
For worker tests, my thinking is that the main page doesn't need to send the tests to the worker, just load a script which is dynamically generated and contains the tests directly.

In this case the HTML page would really just load a script and wait for results as a message. Code would definitely be shared for generating those worker scripts and the Window-scope tests, of course.

**Comment by foolip** [comment]
Another reason to avoid `eval` just came up. I wanted to debug https://mdn-bcd-collector.appspot.com/tests/api/EXT_color_buffer_float, but because all the code is a string it's harder to set a breakpoint. I can set a breakpoint at the `bcd.run()` call and step my way down, but I'd like to just be able to have the code inlined with minimal "stuff" in between that one needs to understand to trust the test results.
