### ISSUE TITLE
Git Flow (or similar) structure?

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#466]
With the addition of our staging branch, I had a thought about restructuring our branches a bit.  I've seen the [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) structure is pretty popular, and our structure is pretty similar (we have feature and hotfix branches that get merged into `main`).

Basically, I'm thinking that we add a new branch -- the `develop` branch -- and organize the other branches just a little bit.  We'd deploy feature additions to the `develop` branch, which is hooked up to our staging URL.  Once we're ready to launch an update, we'll create a new `release` branch and resolve any bugs we find when preparing for a release, which will then be merged into `main` and deploy a new release to the main URL (or we can skip the `release` branches and push directly to `main`).

What do you think, @foolip?

**Comment by foolip** [comment]
I believe the main question here is how we manage deployments to https://mdn-bcd-collector.appspot.com/ vs. https://staging-dot-mdn-bcd-collector.appspot.com/, where currently we deploy `main` to the former and the `staging` branch is used only manually to get the later deployed.

A bunch of debate around feature branches doesn't really apply here, since we don't have long-lived feature development against a code base that's continually changing at the same time, which is a problem in larger software projects. https://github.com/foolip/mdn-bcd-collector/pull/416 might have been our record, and required some merging, but was basically fine. Effectively, we're using feature branches, but in pull requests, and we squash into a linear history.

Back to deployment then. Sometimes we make changes that even with good tests are hard to be totally confident in. https://github.com/foolip/mdn-bcd-collector/pull/470 is a good example, where successfully using the real GitHub API to create a real PR is required to have total confidence.

To allow us to continue moving fast, but allow us to verify that things work in staging after making big changes, I would suggest the following:
- the `main` branch deploys to staging
- a new `prod` branch deploys to production
- the `prod` branch is always trailing the `main` branch, it's not a separate branch that we merge into

What this means is that we can hack way on `main`, and then push to `prod` when we have confidence. We could also take that as an opportunity to review each others changes to `main` where review was skipped.

## Alternatives

Once could also deploy every commit on `main` as its own version of GAE, which in fact we did before commit e7157ef5f342d0a11918372a0735f9e36a1fc4ec. Then one redirects traffic in GCP to push something to prod. We do that for wpt.fyi, but having to clean up old versions regularly is extra work, and I don't think we need the ability to roll back quickly.

Another alternative is to create a staging deployment for every PR for verification. We again do this for wpt.fyi, but again it results in a lot of deployments to manage.
