### ISSUE TITLE
Custom tests: import other custom tests?

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#500]
One thing I noticed is that a lot of APIs I've had to write custom tests for depend on other APIs (such as how the `AudioNode` depends on `AudioContext`).  As a result, there's a lot of repeated code.  We should implement a form of importing from other tests to reduce the amount of duplicate code.

I'm thinking of a syntax roughly along the lines of `<%ident:varname%>`, where the `ident` is the identifier to copy from, and the `varname` is what to rename the `instance` variable to.

**Comment by foolip** [comment]
https://github.com/foolip/mdn-bcd-collector/pull/502 looks good, I'd had something like this in mind as well but never worked on it.

One thing that might still be improved is the readability or compactness of the resulting tests. For that, I think there's some overlap with how we might go about automatically generating expressions like `navigator.mediaDevices` from Web IDL that we know will be a `MediaDevices` instance because we have the `navigator` attribute of type `Navigator` on `Window`, and then a `mediaDevices` attribute of type `MediaDevices` on `Navigator`. It might be similar because it's about chaining expressions together.

No concrete proposal for now, but let's see where things go from here.
