### ISSUE TITLE
Curious no-op promise handlers generated

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#808]
http://mdn-bcd-collector.appspot.com/tests/api/MediaStreamAudioSourceNode has `promise.then(function () {})` generated as one line of code. This might have the effect of avoiding an unhandled promise rejection in some cases, but that doesn't seem like something we would want to do. In this case, `promise` is later reassigned, so whatever `promise` was initially no longer matters to the outcome of the test.

**Comment by vinyldarkscratch** [comment]
It's actually an intentional addition -- for some odd reason, promises imported in other custom tests were chaining promises in certain Chrome versions, which from my research...isn't supposed to happen.  As a result, the value processing callback was getting called twice: once for the main feature, and once for the feature performing the import.  This was the only way I could figure out to resolve the issue...  :(

**Comment by foolip** [comment]
It sounds like the `promise` variable is scoped incorrectly and is being accidentally shared between tests. Or where is it declared and initialized?

**Comment by vinyldarkscratch** [comment]
That's the weird thing about it: the variable shouldn't be shared in the first place, because each test has its own, isolated code to run.  Imports are simply including the JavaScript code.  So, why it's chaining the promises is beyond me...
