### ISSUE TITLE
toString and toJSON tests should be strict about own prototype

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#841]
The current test in http://mdn-bcd-collector.appspot.com/tests/api/Location/toString is:
```js
(function () {
  var instance = window.location;
  return 'toString' in instance;
})();
```

Because of `Object.prototype.toString`, this will always return true. The purpose of `toString` overrides is precisely to override the default behavior, and these tests should rather check for `'toString' in Location.prototype`.

The situation with `toJSON` is similar, except there is no `Object.prototype.toJSON`, but it is often defined at multiple levels of the prototype chain.

We should check for other things that per spec should be on multiple levels of the prototype chain, and make sure we handle all of those correct too. I'm pretty sure this will be the case for some symbols.

One way to go about this would be to implement https://github.com/foolip/mdn-bcd-collector/issues/523 and then have the update script handle these things.

**Comment by foolip** [comment]
https://drafts.fxtf.org/geometry/ the main example I know of where `toJSON` appears at multiple levels. It's also the case with `PerformanceEntry` and things that inherit from it, but they're spread out across many specs.

**Comment by foolip** [comment]
This seems to remain an issue for some tests: https://github.com/mdn/browser-compat-data/pull/7842#discussion_r542944431

**Comment by foolip** [comment]
Yep, this is a mess: https://github.com/mdn/browser-compat-data/pull/10239#issuecomment-833383587

**Comment by jugglinmike** [comment]
I agree with the intent of this issue, but I think [the semantics of the `in` operator](https://tc39.es/ecma262/#sec-relational-operators) make it unsuitable for conformance testing. Since [the prototype of the `Location` prototype is the `Object` prototype](https://webidl.spec.whatwg.org/#interface-prototype-object), a test like `'toString' in Location.prototype` is also subject to false positives.

Case in point: [the `toString` in question is specified as an "own" property of the `Location` instance](https://webidl.spec.whatwg.org/#es-stringifier), so if that particular test references `Location.prototype`, it should probably assert the *absence* of an "own" property (though that may be too prescriptive--I don't know HTML's policy for host-defined methods).
