### ISSUE TITLE
Store whether the test was run in a secure context in the result JSON

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#987]
For the same reason as why I filed #986, we should probably store whether or not the run was done from a secure context, and give a warning when updating BCD if some runs were done from an insecure context.

Or maybe we should just disallow runs from insecure contexts in general?

(Obviously we can't _always_ check if we're on a secure context in older browsers, but we can at least handle the case when we _know_ we're in an insecure context.)

**Comment by foolip** [comment]
Detecting this and storing it in the report seems like a good idea.

Originally I wanted to run all tests in both secure and non-secure contexts to be able to infer whether secure context is required, but we abandoned that idea along the way as there aren't that many APIs which have gone through a change to require secure contexts, so automating it is not worth the complexity.

In order to allow antiques browsers to run HTTP still needs to be supported, but it shouldn't happen by accident which it now can.

**Comment by foolip** [comment]
There is a warning shown on the collector front page if not using HTTPS now, try http://mdn-bcd-collector.gooborg.com/.

I think that mostly solves this issue, but if not please file a new one at https://github.com/openwebdocs/mdn-bcd-collector/issues.
